version: '3'
services:
  bot:
    build:
      dockerfile: services/bot/Dockerfile
      context: .
    environment:
      BOARDS_URL: http://boards.chess.pleb.xyz
      DISCORD_COMMAND_PREFIX: ','
  gateway:
    build:
      dockerfile: services/gateway/Dockerfile
      context: .
  proxy:
    build:
      dockerfile: services/proxy/Dockerfile
      context: .
  api:
    build:
      dockerfile: services/api/Dockerfile
      context: .
  boards:
    build:
      dockerfile: services/boards/Dockerfile
      context: .
  rabbit:
    image: rabbitmq:3-management
    ports:
      - 15672:15672
  redis:
    volumes:
      - ./data/redis:/data
  postgres:
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
  nginx:
    ports:
      - 8081:80
