version: '3'
services:
  bot:
    environment:
      AMQP_URL: rabbit
      API_URL: http://api:8080
    env_file: .env
  gateway:
    environment:
      AMQP_URL: amqp://rabbit
    env_file: .env
  proxy:
    environment:
      REDIS_URL: redis://redis
      AMQP_URL: amqp://rabbit/%2f
      RUST_LOG: info
    env_file: .env
  api:
    env_file: .env
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/postgres
    expose:
      - "8080"
  boards:
    expose:
      - "8081"
  rabbit:
    image: rabbitmq
  redis:
    image: redis
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
  nginx:
    image: nginx
    volumes:
      - ./services/nginx:/etc/nginx:ro
