version: '3'
services:
  bot:
    image: docker.pkg.github.com/appellation/chess/bot
  gateway:
    image: docker.pkg.github.com/appellation/chess/gateway
  proxy:
    image: docker.pkg.github.com/appellation/chess/proxy
  api:
    image: docker.pkg.github.com/appellation/chess/api
  boards:
    image: docker.pkg.github.com/appellation/chess/boards
  postgres:
    volumes:
      - postgres_data:/var/lib/postgresql
  redis:
    volumes:
      - redis_data:/data
  nginx:
    ports:
      - 80:80

volumes:
  postgres_data:
  redis_data:
