version: '3'
services:
  bot:
    build:
      dockerfile: services/bot/Dockerfile
      context: .
  gateway:
    build:
      dockerfile: services/gateway/Dockerfile
      context: .
  proxy:
    build:
      dockerfile: services/proxy/Dockerfile
      context: .
  api:
    build:
      dockerfile: services/api/Dockerfile
      context: .
