version: '3'
services:
  bot:
    build:
      dockerfile: services/bot/Dockerfile
      context: .
  gateway:
    build:
      dockerfile: services/gateway/Dockerfile
      context: .
  proxy:
    build:
      dockerfile: services/proxy/Dockerfile
      context: .
  api:
    build:
      dockerfile: services/api/Dockerfile
      context: .
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/postgres
  rabbit:
    image: rabbitmq:3-management
    ports:
      - 15672:15672
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
